services:
  api:
    build: .
    working_dir: /app
    volumes:
      - ./:/app
    env_file: .env
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
